---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewalld on master nodes
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 22
    - 80
    - 443
    - 6443
    - 2379-2380
    - 10250-10252
    - 30000-32767

- name: Open calico UDP ports
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
  loop:
    - 4789

- name: Open calico TCP ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 5473
    - 179

- name: Reload firewalld
  shell: firewall-cmd --reload
